apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: idletest
  name: idletest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: idletest
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: idletest
    spec:
      containers:
      - image: docker.io/yahyaalshamrani/idletest:v2.0
        name: idletest
        ports:
        - containerPort: 8080
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: idletest
  name: idletest
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: idletest
status:
  loadBalancer: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: idletest
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "10"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "10"
    nginx.ingress.kubernetes.io/proxy-next-upstream-timeout: "0"
    nginx.ingress.kubernetes.io/proxy-next-upstream-tries: "1"
spec:
  ingressClassName: nginx
  rules:
  - host: myapp.local
    http:
      paths:
      - backend:
          service:
            name: idletest
            port:
              number: 8080
        path: /
        pathType: Prefix
status:
  loadBalancer: {}
