apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: idletest
  name: idletest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: idletest
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: idletest
    spec:
      containers:
      - image: ruh.ocir.io/axgo6vn5jkra/yalshamrani/idletest:v2.3
        name: idletest
        env:
        - name: INGRESS_GATEWAY_ENABLED
          value: "true"
        - name: INGRESS_GATEWAY_HOST
          value: gateway.example.com
        - name: INGRESS_GATEWAY_PATH
          value: /xyz
        ports:
        - containerPort: 8080
        resources: {}
      imagePullSecrets:
        - name: oci-pull-secret
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: idletest
  name: idletest
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: idletest
status:
  loadBalancer: {}
